[build]
beforeBuildCommand = "trunk build"
beforeDevCommand = "trunk serve"
devPath = "http://localhost:3030"
distDir = "../dist"
withGlobalTauri = true

[package]
productName = "lab1"
version = "0.1.0"

[tauri.allowlist]
dialog.save = true

[tauri.bundle]
active = true
category = "DeveloperTool"
copyright = ""
externalBin = [ ]
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
identifier = "com.tauri.b1"
longDescription = ""
resources = [ ]
shortDescription = ""
targets = "all"

  [tauri.bundle.deb]
  depends = [ ]

  [tauri.bundle.macOS]
  exceptionDomain = ""
  frameworks = [ ]

  [tauri.bundle.windows]
  digestAlgorithm = "sha256"
  timestampUrl = ""

[tauri.security]

[tauri.updater]
active = false

[[tauri.windows]]
fullscreen = false
height = 600
resizable = false
title = "lab"
width = 800
